[package]
name = "xcm-fee-payment-runtime-api"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
repository.workspace = true
description = "XCM fee payment runtime API"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = [
	"derive",
] }

sp-api = { path = "../../../substrate/primitives/api", default-features = false }
scale-info = { version = "2.11.1", default-features = false, features = [
	"derive",
	"serde",
] }
sp-std = { path = "../../../substrate/primitives/std", default-features = false }
sp-runtime = { path = "../../../substrate/primitives/runtime", default-features = false }
sp-weights = { path = "../../../substrate/primitives/weights", default-features = false }
xcm = { package = "staging-xcm", path = "../", default-features = false }
frame-support = { path = "../../../substrate/frame/support", default-features = false }

[dev-dependencies]
frame-system = { path = "../../../substrate/frame/system", default-features = false }
pallet-xcm = { path = "../pallet-xcm", default-features = false }
xcm-builder = { package = "staging-xcm-builder", path = "../xcm-builder", default-features = false }
sp-io = { path = "../../../substrate/primitives/io", default-features = false }
pallet-balances = { path = "../../../substrate/frame/balances", default-features = false }
pallet-assets = { path = "../../../substrate/frame/assets", default-features = false }
xcm-executor = { package = "staging-xcm-executor", path = "../xcm-executor", default-features = false }
frame-executive = { path = "../../../substrate/frame/executive", default-features = false }
log = { workspace = true }
env_logger = "0.9.0"

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-support/std",
	"scale-info/std",
	"sp-api/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-weights/std",
	"xcm/std",
	"frame-system/std",
	"pallet-xcm/std",
	"xcm-builder/std",
	"sp-io/std",
	"pallet-balances/std",
	"pallet-assets/std",
	"xcm-executor/std",
	"frame-executive/std",
]
